files:
  - source: /quickshop-bukkit/src/main/resources/lang/*.json
    translation: /crowdin/lang/%locale%/%original_file_name%
  - source: /quickshop-bukkit/src/main/resources/lang/*.yml
    translation: /crowdin/lang/%locale%/%original_file_name%