#Should we prevent the creation of a shop or trade with a shop outside Factions's area?
whitelist-mode: true
#Which checks does a player need to pass to create a shop?
create:
  #Factions requires the status to match with these:
  require:
    open: false
    normal: true
    wilderness: false
    peaceful: true
    permanent: false
    safezone: false
    own: false
    warzone: false
      #The player must have these flags in the faction:
  flags:
    - CONTAINER
    - ECONOMY
  #Which checks does a player need to pass to trade with a shop?
trade:
  #Factions requires the status to match with these:
  require:
    open: false
    normal: true
    wilderness: false
    peaceful: false
    permanent: false
    safezone: false
    own: false
    warzone: false
    #The player must have these flags in the faction:
  flags: [ ]