name: qscompat-${artifactId}
version: '${project.version}'
main: com.ghostchu.quickshop.compatibility.${artifactId}.Main
api-version: 1.16
depend:
  - ClearLag
  - QuickShop-Hikari
authors: [ Ghost_chu ]
description: Compatibility module for ClearLagg
