name: qscompat-griefprevention
version: '${project.version}'
main: com.ghostchu.quickshop.compatibility.griefprevention.Griefprevention
api-version: 1.16
depend: [ GriefPrevention, QuickShop-Hikari ]
