name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release
      - hikari
  push:
    branches:
      - main
      - release
      - hikari

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v4.2.2
        with:
          linter: jetbrains/qodana-java
