name: Qodana License Audit
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release
      - hikari
  push:
    branches:
      - main
      - release
      - hikari

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Qodana - License Audit
        uses: JetBrains/qodana-license-audit-action@v2.0-eap
